var exports = module.exports = {};

/****** requires ******/

var mongoose = require('mongoose');
var passwordHash = require('password-hash');

/***** connect to db *****/

var dbPlayers = mongoose.createConnection('mongodb://localhost/players');

/****** schemas/models ******/

var guestSchema = mongoose.Schema({
    "tutorial" : Number
});

var playerSchema = mongoose.Schema({
    "email": String,
    "username": String,
    "password": String,
    "cardCollection": {
        "coreSet": {
            "1": Number,
            "2": Number,
            "3": Number,
            "4": Number,
            "5": Number,
            "6": Number,
            "7": Number,
            "8": Number,
            "9": Number,
            "10": Number,
            "11": Number,
            "12": Number,
            "13": Number,
            "14": Number,
            "15": Number,
            "16": Number,
            "17": Number,
            "18": Number,
            "19": Number,
            "20": Number,
            "21": Number,
            "22": Number,
            "23": Number,
            "24": Number,
            "25": Number,
            "26": Number,
            "27": Number,
            "28": Number,
            "29": Number,
            "30": Number,
            "31": Number,
            "32": Number,
            "33": Number,
            "34": Number,
            "35": Number,
            "36": Number,
            "37": Number,
            "38": Number,
            "39": Number,
            "40": Number,
            "41": Number,
            "42": Number,
            "43": Number,
            "44": Number,
            "45": Number,
            "46": Number,
            "47": Number,
            "48": Number,
            "49": Number,
            "50": Number,
            "51": Number,
            "52": Number,
            "53": Number,
            "54": Number,
            "55": Number,
            "56": Number,
            "57": Number,
            "58": Number,
            "59": Number,
            "60": Number,
            "61": Number,
            "62": Number,
            "63": Number,
            "64": Number,
            "65": Number,
            "66": Number,
            "67": Number,
            "68": Number,
            "69": Number,
            "70": Number,
            "71": Number,
            "72": Number,
            "73": Number,
            "74": Number,
            "75": Number,
            "76": Number,
            "77": Number,
            "78": Number,
            "79": Number,
            "80": Number,
            "81": Number,
            "82": Number,
            "83": Number,
            "84": Number,
            "85": Number,
            "86": Number,
            "87": Number,
            "88": Number,
            "89": Number,
            "90": Number,
            "91": Number,
            "92": Number,
            "93": Number,
            "94": Number,
            "95": Number,
            "96": Number,
            "97": Number,
            "98": Number,
            "99": Number,
            "100": Number,
            "101": Number,
            "102": Number,
            "103": Number,
            "104": Number,
            "105": Number,
            "106": Number,
            "107": Number,
            "108": Number,
            "109": Number,
            "110": Number,
            "111": Number,
            "112": Number,
            "113": Number,
            "114": Number,
            "115": Number,
            "116": Number,
            "117": Number,
            "118": Number,
            "119": Number,
            "120": Number,
            "121": Number,
            "122": Number,
            "123": Number,
            "124": Number,
            "125": Number,
            "126": Number,
            "127": Number,
            "128": Number,
            "129": Number,
            "130": Number,
            "131": Number,
            "132": Number,
            "133": Number,
            "134": Number,
            "135": Number,
            "136": Number,
            "137": Number,
            "138": Number,
            "139": Number,
            "140": Number,
            "141": Number,
            "142": Number,
            "143": Number,
            "144": Number,
            "145": Number,
            "146": Number,
            "147": Number,
            "148": Number,
            "149": Number,
            "150": Number,
            "151": Number,
            "152": Number,
            "153": Number,
            "154": Number,
            "155": Number,
            "156": Number,
            "157": Number,
            "158": Number,
            "159": Number,
            "160": Number,
            "161": Number,
            "162": Number,
            "163": Number,
            "164": Number,
            "165": Number,
            "166": Number,
            "167": Number,
            "168": Number,
            "169": Number,
            "170": Number,
            "171": Number,
            "172": Number,
            "173": Number,
            "174": Number,
            "175": Number,
            "176": Number,
            "177": Number,
            "178": Number,
            "179": Number,
            "180": Number,
            "181": Number,
            "182": Number,
            "183": Number,
            "184": Number,
            "185": Number,
            "186": Number,
            "187": Number,
            "188": Number,
            "189": Number,
            "190": Number,
            "191": Number,
            "192": Number,
            "193": Number,
            "194": Number,
            "195": Number,
            "196": Number,
            "197": Number,
            "198": Number,
            "199": Number,
            "200": Number,
            "201": Number,
            "202": Number,
            "203": Number,
            "204": Number,
            "205": Number,
            "206": Number,
            "207": Number,
            "208": Number,
            "209": Number,
            "210": Number,
            "211": Number,
            "212": Number,
            "213": Number,
            "214": Number,
            "215": Number,
            "216": Number,
            "217": Number,
            "218": Number,
            "219": Number,
            "220": Number,
            "221": Number,
            "222": Number,
            "223": Number,
        },
    },
    "credits": Number,
    "rank": Number, // more like clash of clans/chess rankings
});

var playerModel = dbPlayers.model("players", playerSchema);

/****** exports ******/

exports.sessionSchema = mongoose.Schema({
    _id: Number,
    pI: Number,
});

exports.checkEmail = function(email, callback){
    playerModel.findOne({"email": email}, function(err, obj){
        if (obj !== null) {
            callback(true);
        } else {
            callback(false);
        }
    })
}

exports.createNewAccount = function(data){
    var newPlayer = new playerModel({
        "email": data.email,
        "username": data.username,
        "password": passwordHash.generate(data.password, {saltLength: 16}),
        "cardCollection": {
            "coreSet": {
                "1": 0,
                "2": 0,
                "3": 0,
                "4": 0,
                "5": 0,
                "6": 0,
                "7": 0,
                "8": 0,
                "9": 0,
                "10": 0,
                "11": 0,
                "12": 0,
                "13": 0,
                "14": 0,
                "15": 0,
                "16": 0,
                "17": 0,
                "18": 0,
                "19": 0,
                "20": 0,
                "21": 0,
                "22": 0,
                "23": 0,
                "24": 0,
                "25": 0,
                "26": 0,
                "27": 0,
                "28": 0,
                "29": 0,
                "30": 0,
                "31": 0,
                "32": 0,
                "33": 0,
                "34": 0,
                "35": 0,
                "36": 0,
                "37": 0,
                "38": 0,
                "39": 0,
                "40": 0,
                "41": 0,
                "42": 0,
                "43": 0,
                "44": 0,
                "45": 0,
                "46": 0,
                "47": 0,
                "48": 0,
                "49": 0,
                "50": 0,
                "51": 0,
                "52": 0,
                "53": 0,
                "54": 0,
                "55": 0,
                "56": 0,
                "57": 0,
                "58": 0,
                "59": 0,
                "60": 0,
                "61": 0,
                "62": 0,
                "63": 0,
                "64": 0,
                "65": 0,
                "66": 0,
                "67": 0,
                "68": 0,
                "69": 0,
                "70": 0,
                "71": 0,
                "72": 0,
                "73": 0,
                "74": 0,
                "75": 0,
                "76": 0,
                "77": 0,
                "78": 0,
                "79": 0,
                "80": 0,
                "81": 0,
                "82": 0,
                "83": 0,
                "84": 0,
                "85": 0,
                "86": 0,
                "87": 0,
                "88": 0,
                "89": 0,
                "90": 0,
                "91": 0,
                "92": 0,
                "93": 0,
                "94": 0,
                "95": 0,
                "96": 0,
                "97": 0,
                "98": 0,
                "99": 0,
                "100": 0,
                "101": 0,
                "102": 0,
                "103": 0,
                "104": 0,
                "105": 0,
                "106": 0,
                "107": 0,
                "108": 0,
                "109": 0,
                "110": 0,
                "111": 0,
                "112": 0,
                "113": 0,
                "114": 0,
                "115": 0,
                "116": 0,
                "117": 0,
                "118": 0,
                "119": 0,
                "120": 0,
                "121": 0,
                "122": 0,
                "123": 0,
                "124": 0,
                "125": 0,
                "126": 0,
                "127": 0,
                "128": 0,
                "129": 0,
                "130": 0,
                "131": 0,
                "132": 0,
                "133": 0,
                "134": 0,
                "135": 0,
                "136": 0,
                "137": 0,
                "138": 0,
                "139": 0,
                "140": 0,
                "141": 0,
                "142": 0,
                "143": 0,
                "144": 0,
                "145": 0,
                "146": 0,
                "147": 0,
                "148": 0,
                "149": 0,
                "150": 0,
                "151": 0,
                "152": 0,
                "153": 0,
                "154": 0,
                "155": 0,
                "156": 0,
                "157": 0,
                "158": 0,
                "159": 0,
                "160": 0,
                "161": 0,
                "162": 0,
                "163": 0,
                "164": 0,
                "165": 0,
                "166": 0,
                "167": 0,
                "168": 0,
                "169": 0,
                "170": 0,
                "171": 0,
                "172": 0,
                "173": 0,
                "174": 0,
                "175": 0,
                "176": 0,
                "177": 0,
                "178": 0,
                "179": 0,
                "180": 0,
                "181": 0,
                "182": 0,
                "183": 0,
                "184": 0,
                "185": 0,
                "186": 0,
                "187": 0,
                "188": 0,
                "189": 0,
                "190": 0,
                "191": 0,
                "192": 0,
                "193": 0,
                "194": 0,
                "195": 0,
                "196": 0,
                "197": 0,
                "198": 0,
                "199": 0,
                "200": 0,
                "201": 0,
                "202": 0,
                "203": 0,
                "204": 0,
                "205": 0,
                "206": 0,
                "207": 0,
                "208": 0,
                "209": 0,
                "210": 0,
                "211": 0,
                "212": 0,
                "213": 0,
                "214": 0,
                "215": 0,
                "216": 0,
                "217": 0,
                "218": 0,
                "219": 0,
                "220": 0,
                "221": 0,
                "222": 0,
                "223": 0,
            },
        },
        "credits": 0, //
        "rank": 1000, //
    });
    newPlayer.save(function(err, newPlayer){});
}

exports.checkLogin = function(data, callback){
    playerModel.findOne({"email": data.email}, function(err, player){
        if (player !== null) {
            if (passwordHash.verify(data.password, player.password)) {
                callback([player._id]);
            } else {
                callback("Bad password");
            }
        } else {
            callback("Email not found");
        }
    });
}

exports.getPlayerInfo = function(id, callback){
    playerModel.findOne({"_id": id}, function(err, player){
        if (player !== null) {
            callback(player);
        } else {
            callback(false);
        }
    });
}

